language: python

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

addons:
    apt:
        packages:
            - libc6-i386
            - libusb-1.0-0-dev

env:
    - TRAVIS_CI=1 USE_MAG=1 USE_BARO=1 USE_SONAR=1 USE_LIDAR_LITE=1 USE_FLOW_SENSOR=1 UART_DEBUG=1 ONESHOT125=1 DEBUG=1 STEP_ACRO_SELF_LEVEL=1 STEP_ALTITUDE_HOLD=1 STEP_HEADING_HOLD=1
    - TRAVIS_CI=1 USE_MAG=0 USE_BARO=0 USE_SONAR=0 USE_LIDAR_LITE=0 USE_FLOW_SENSOR=0 UART_DEBUG=1 ONESHOT125=1 DEBUG=1 STEP_ACRO_SELF_LEVEL=0 STEP_ALTITUDE_HOLD=0 STEP_HEADING_HOLD=0
    - TRAVIS_CI=1 USE_MAG=1 USE_BARO=1 USE_SONAR=1 USE_LIDAR_LITE=1 USE_FLOW_SENSOR=1 UART_DEBUG=1 ONESHOT125=1 DEBUG=0 STEP_ACRO_SELF_LEVEL=0 STEP_ALTITUDE_HOLD=0 STEP_HEADING_HOLD=0
    - TRAVIS_CI=1 USE_MAG=1 USE_BARO=1 USE_SONAR=1 USE_LIDAR_LITE=1 USE_FLOW_SENSOR=1 UART_DEBUG=1 ONESHOT125=0 DEBUG=0 STEP_ACRO_SELF_LEVEL=0 STEP_ALTITUDE_HOLD=0 STEP_HEADING_HOLD=0
    - TRAVIS_CI=1 USE_MAG=0 USE_BARO=0 USE_SONAR=0 USE_LIDAR_LITE=0 USE_FLOW_SENSOR=0 UART_DEBUG=1 ONESHOT125=1 DEBUG=0 STEP_ACRO_SELF_LEVEL=0 STEP_ALTITUDE_HOLD=0 STEP_HEADING_HOLD=0
    - TRAVIS_CI=1 USE_MAG=1 USE_BARO=1 USE_SONAR=1 USE_LIDAR_LITE=1 USE_FLOW_SENSOR=1 UART_DEBUG=0 ONESHOT125=1 DEBUG=0 STEP_ACRO_SELF_LEVEL=0 STEP_ALTITUDE_HOLD=0 STEP_HEADING_HOLD=0
    - TRAVIS_CI=1 USE_MAG=0 USE_BARO=0 USE_SONAR=0 USE_LIDAR_LITE=0 USE_FLOW_SENSOR=0 UART_DEBUG=0 ONESHOT125=1 DEBUG=0 STEP_ACRO_SELF_LEVEL=0 STEP_ALTITUDE_HOLD=0 STEP_HEADING_HOLD=0
    - TRAVIS_CI=1 USE_MAG=1 USE_BARO=1 USE_SONAR=0 USE_LIDAR_LITE=0 USE_FLOW_SENSOR=0 UART_DEBUG=1 ONESHOT125=1 DEBUG=0 STEP_ACRO_SELF_LEVEL=0 STEP_ALTITUDE_HOLD=0 STEP_HEADING_HOLD=0
    - TRAVIS_CI=1 USE_MAG=1 USE_BARO=0 USE_SONAR=1 USE_LIDAR_LITE=0 USE_FLOW_SENSOR=0 UART_DEBUG=1 ONESHOT125=1 DEBUG=0 STEP_ACRO_SELF_LEVEL=0 STEP_ALTITUDE_HOLD=0 STEP_HEADING_HOLD=0
    - TRAVIS_CI=1 USE_MAG=1 USE_BARO=0 USE_SONAR=0 USE_LIDAR_LITE=1 USE_FLOW_SENSOR=0 UART_DEBUG=1 ONESHOT125=1 DEBUG=0 STEP_ACRO_SELF_LEVEL=0 STEP_ALTITUDE_HOLD=0 STEP_HEADING_HOLD=0
    - TRAVIS_CI=1 USE_MAG=1 USE_BARO=0 USE_SONAR=0 USE_LIDAR_LITE=0 USE_FLOW_SENSOR=1 UART_DEBUG=1 ONESHOT125=1 DEBUG=0 STEP_ACRO_SELF_LEVEL=0 STEP_ALTITUDE_HOLD=0 STEP_HEADING_HOLD=0

install:
    - wget "https://launchpad.net/gcc-arm-embedded/4.8/4.8-2014-q3-update/+download/gcc-arm-none-eabi-4_8-2014q3-20140805-linux.tar.bz2"
    - tar -xf gcc-arm-none-eabi-4_8-2014q3-20140805-linux.tar.bz2
    - export PATH=$PATH:$PWD/gcc-arm-none-eabi-4_8-2014q3/bin
    - git clone https://github.com/utzig/lm4tools.git
    - make -j2 -C lm4tools/lm4flash all
    - export PATH=$PATH:$PWD/lm4tools/lm4flash
    - pip install -U platformio

before_script:
    - arm-none-eabi-gcc --version
    - lm4flash -V

script:
    - platformio run -e lptm4c1230c3pm_ci
    - make -j2 -C src/
